# .github/workflows/release.yml
name: Release

permissions:
  contents: write

on:
  push:
    branches:
      - "main" # 或改成 main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

                    - name: Compile
         id: compile
         uses: rust-build/rust-build.action@v1.4.5
         with:
           TOOLCHAIN_VERSION: nightly
           RUSTTARGET: x86_64-unknown-linux-musl
           UPLOAD_MODE: none
           ARCHIVE_TYPES: none

       - name: Upload executable
         uses: actions/upload-artifact@v4
         with:
           name: rs-counter-linux-x86_64
           path: ${{ steps.compile.outputs.BUILT_EXECUTABLE }}
