# .github/workflows/release.yml
name: Release
permissions:
  contents: write
on:
  push:
    branches: "*"
    # tags:
    #   - v[0-9]+.*
    # branches:
    #   - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - name: Compile
        id: compile
        uses: rust-build/rust-build.action@v1.4.5
        with:
          toolchain-version: nightly
          RUSTTARGET: x86_64-unknown-linux-musl
          UPLOAD_MODE: none
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Binary
          path: |
            ${{ steps.compile.outputs.BUILT_ARCHIVE }}
            ${{ steps.compile.outputs.BUILT_CHECKSUM }}
